### ISSUE TITLE
xkeysym::NO_SYMBOL not part of xkeysym::key

### ISSUE THREAD

**Issue by pentamassiv** [rust-windowing/xkeysym#16]
`NO_SYMBOL` is not part of the `xkeysym::key` module. This is a little unfortunate, because I need to use it and so far only have `xkbcommon` as an explicit dependency. `xkbcommon` does not export the `NO_SYMBOL`, so I would have to add `xkeysym` explicitly, or use `Keysym(0)`. It would be more convenient, if I could use it just like all the other `KeySym`.

**Comment by notgull** [comment]
I would accept a PR to add `NO_SYMBOL` to the `key` module.
